#!/bin/bash

# Stripe Webhook Configuration Quick Start
# Este script te guía a través de la configuración del webhook

echo "🎯 Configuración de Webhook Stripe - Guía Rápida"
echo "=================================================="
echo ""

# Mostrar claves
echo "✅ Tus Claves (Entorno Test):"
echo ""
echo "📌 Publishable Key:"
echo "pk_test_51SuUod2KaK54WVOoow3ceAdHyLefry0S7wHHA5R0SfjFyB9mVyfwpocCmt0adzDFDiwsaM4diLCht1E98oJV8UWU00H20ta2MQ"
echo ""
echo "📌 Secret Key:"
echo "sk_test_51SuUod2KaK54WVOoDRRDNKAb4BoDBWT6pycLg45iSQIMDIrR1kfWd3GP9K1pDdAubZqChuHIA24o7MsmukcTFC53009adHE2Hl"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "PASO 1: Configurar Webhook en Stripe Dashboard"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1. Ve a: https://dashboard.stripe.com/webhooks"
echo "2. Click en 'Add an endpoint'"
echo "3. Ingresa esta URL:"
echo "   https://europe-west1-aparcamientodisponible.cloudfunctions.net/stripeWebhook"
echo ""
echo "4. Selecciona estos eventos:"
echo "   ✓ payment_intent.succeeded"
echo "   ✓ payment_intent.payment_failed"
echo "   ✓ charge.refunded"
echo ""
echo "5. Click en 'Add endpoint'"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "PASO 2: Copiar Webhook Signing Secret"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1. En Stripe Dashboard, haz click en tu nuevo endpoint"
echo "2. Copia el 'Signing Secret' (empieza con whsec_)"
echo "3. Guarda en functions/.env.local:"
echo ""
echo "   STRIPE_WEBHOOK_SECRET=whsec_test_XXXXXXXXXXXXX"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "PASO 3: Desplegar Cloud Functions"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Ejecuta estos comandos:"
echo ""
echo "  cd functions"
echo "  npm install stripe firebase-admin firebase-functions"
echo "  cd .."
echo "  firebase deploy --only functions"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "PASO 4: Probar el Webhook"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Opción A - Test desde Stripe Dashboard:"
echo "  1. Vuelve a Stripe > Webhooks > Tu endpoint"
echo "  2. Scroll a 'Event deliveries'"
echo "  3. Click 'Send test event'"
echo "  4. Selecciona 'charge.succeeded'"
echo "  5. Click 'Send event'"
echo "  6. Verifica que reciba respuesta ✅ 200"
echo ""
echo "Opción B - Test desde tu App:"
echo "  1. flutter run -d chrome"
echo "  2. Navega a cualquier plaza"
echo "  3. Click en 'Pagar'"
echo "  4. Selecciona método: Tarjeta"
echo "  5. Usa: 4242 4242 4242 4242 | 12/25 | 123"
echo "  6. Completa el pago"
echo "  7. Verifica en Stripe > Webhooks > Event deliveries"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "📋 Checklist"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  [ ] Webhook endpoint creado en Stripe"
echo "  [ ] Signing Secret copiado a functions/.env.local"
echo "  [ ] Cloud Functions desplegadas"
echo "  [ ] Test event enviado y recibido ✅"
echo "  [ ] Primer pago de prueba completado"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo "🔗 URLs Importantes"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "📌 Dashboard: https://dashboard.stripe.com"
echo "📌 Webhooks: https://dashboard.stripe.com/webhooks"
echo "📌 Events: https://dashboard.stripe.com/events"
echo "📌 Guía: STRIPE_WEBHOOK_SETUP.md"
echo ""

echo "✅ ¡Listo! Tu webhook está configurado."
