# This is a basic workflow to compile APK flutter

name: Flutter APK CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master"]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./aparcamientoszaragoza

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository Flutter
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo ### Hello Flutter CI! ###

      # Runs a JAVA
      - name: Configurate JAVA
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '19'
          distribution: 'zulu' 

      # Flutter actions setup
      - name: Flutter actions setup
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta'

      # Flutter change directory
      - name: Flutter No interactions
        run: flutter config --no-cli-animations

      # Flutter LS
      - name: Flutter LIST
        run: ls -la

      # Flutter PWD
      - name: Flutter PWD
        run: pwd

      # Flutter pub get
      - name: Flutter GET
        run: flutter pub get

      # Flutter format
      #- name: Flutter FORMAT
      #  run: flutter format --set-exit-if-changed

      # Flutter ANALYZE
      #- name: Flutter ANALYZE
      #  run: flutter analyze .

      # Flutter BUILD
      - name: Flutter BUILD
        run: flutter build apk

      # Flutter LS
      - name: Flutter LIST
        run: ls -la build/app/outputs/flutter-apk

      # Flutter deploy APK
      - name: Flutter DEPLOY APK
        uses: actions/upload-artifact@v4.3.3
        with:
          name: release-apk
          path: ./aparcamientoszaragoza/build/app/outputs/flutter-apk/app-release.apk

