name: Docker Image to Google Cloud

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:

  PROJECT_ID: aparcamientodisponible
  GAR_LOCATION: us-central1
  REGION: us-central1
  APP: gcf-artifacts

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4
      name: Checkout code

    - name: 'Google auth'
      id: 'auth'
      uses: 'google-github-actions/auth@v2.1.2'
      with:
        credentials_json: '${{ secrets.GOOGLE_ACCOUNT_JSON }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        project_id: '${{ env.PROJECT_ID }}'

    - name: 'Docker auth'
      run: |-
         gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

    - name: 'Build and push container'
      run: |-
         docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.APP }}/${{ env.APP }}:${{ github.sha }}" ./
         docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.APP }}/${{ env.APP }}:${{ github.sha }}"

    - name: 'Create release name'
      run: |-
         echo "RELEASE_NAME=${{ env.APP }}-${GITHUB_SHA::7}-${GITHUB_RUN_NUMBER}" >> ${GITHUB_ENV}

    - name: 'Create Cloud Deploy release'
      uses: 'google-github-actions/create-cloud-deploy-release@v0'
      with:
        delivery_pipeline: '${{ env.APP }}'
        name: '${{ env.RELEASE_NAME }}'
        region: '${{ env.REGION }}'
        description: '${{ env.GITHUB_COMMIT_MSG }}'
        images: 'demo-app=${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.APP }}/${{ env.APP }}:${{ github.sha }}'
        source: 'demo-app'

    
